version: '3.8'

services:
  # go_app
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/dockerfiles/app/Dockerfile
    volumes: # マウント
      - ./app:/usr/local/go/src/trial-3/app
      - .env:/usr/local/go/src/trial-3/app/.env
    tty: true # コンテナの永続化
    depends_on:
      - db
    ports:
      - ${APP_PORT}:8080

  # postgresql
  db:
    container_name: ${DB_HOST}
    build:
      context: .
      dockerfile: ./build/dockerfiles/db/Dockerfile
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./app/database/init:/docker-entrypoint-initdb.d # DBを初期化
    ports:
      - ${DB_PORT}:5432

volumes:
  db-store:
